title: Ольга Гула
description: Ольга Гула - Cертифікований викладач СELTA
details: Провела понад 5000 занять з англійської мови та навчила більше 600 студентів.

linkedin_username: olha-hula-12a849147
email: hula.teaching@gmail.com
telegram_username: olhahula

# Build settings
markdown: kramdown
